name: Issue 4 Issue

on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.create({
              owner: 'sudorunoscar',
              repo: 'githubactions',
              title: 'Preset Issue Title',
              body: 'Preset issue body'
            })
